info/__init__.py
from logging.handlers import RotatingFileHandler
import logging
from flask import Flask, render_template, g
# 可以用来指定 session 保存的位置
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flask_wtf.csrf import generate_csrf
from redis import StrictRedis
from config import Config
# 初始化数据库
# 在 flask 很多扩展里面都可以先初始化扩展的对象然后去调用 init_app 方法去初始化


db = SQLAlchemy()
redis_store = None  # type: StrictRedis


def setup_log(config_name):
    # 设置日志的记录等级
    logging.basicConfig(level=Config[config_name].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


def create_app(config_name):
    '''通过传入不同配置名i，初始化器对应配置的应用实例'''
    #  配置日志,并且传入配置名字，以便获取到指定配置所对应的日志等级
    setup_log(config_name)
    # 创建 Flask 对象
    app = Flask(__name__)

    # 加载配置
    app.config.from_object(Config[config_name])
    # 配置数据库
    db.init_app(app)
    # 配置redis
    global redis_store
    redis_store = StrictRedis(host=Config[config_name].REDIS_HOST, port=Config[config_name].REDIS_PORT, decode_responses=True)
    # 开启当前项目 CSRF 保护,制作服务器验证功能
    # 帮我们做了：从 cookie 中取出随机值，从表单中取出随机值，然后进行校验，并且响应校验结果
    # 我们需要做：1.在界面加载的时候，往 cookie 中添加一个csrf_token 并且在表单中添加一个隐藏的csrf_token
    CSRFProtect(app)
    # 设置session的保存位置
    Session(app)

    from info.utils.common import do_index_class
    app.add_template_filter(do_index_class, 'index_class')
    # 注册蓝图
    from info.utils.common import user_login_data

    @app.errorhandler(404)
    @user_login_data
    def page_not_found(e):
        user = g.user
        data = {"user": user.to_dict() if user else None}
        return render_template('news/404.html', data=data)

    @app.after_request
    def after_request(response):
        # 生成一个随机的 csrf_token 的值
        csrf_token= generate_csrf()
        # 设置一个 cookie
        response.set_cookie('csrf_token', csrf_token)
        return response
    # 添加模板过滤器

    from info.modules.index import index_blu
    app.register_blueprint(index_blu)

    from info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)

    from info.modules.news import news_blu
    app.register_blueprint(news_blu)

    from info.modules.admin import admin_blu
    app.register_blueprint(admin_blu, url_prefix="/admin")

    from info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)
    return app

info/libs/__init__.py
# 第三方的提供的一些工具都放在当前模块下

info/modules/__init__.py
# 该模块是用于保存当前所有的业务逻辑模块。比如：首页、新闻详情页、个人中心、后台管理

info/modules/admin/__init__.py
# 新闻详情模块的蓝图

from flask import Blueprint

# 创建蓝图对象
from flask import redirect
from flask import request
from flask import session
from flask import url_for

admin_blu = Blueprint("admin", __name__)

from . import views


@admin_blu.before_request
def check_admin():
    # if 不是管理员，那么直接跳转到主页
    is_admin = session.get("is_admin", False)
    # if not is_admin and 当前访问的url不是管理登录页:
    if not is_admin and not request.url.endswith(url_for('admin.login')):
        return redirect('/')

info/modules/admin/views.py
import time
from datetime import datetime, timedelta
from flask import render_template, request, session, redirect, url_for, jsonify, g, current_app, abort

from info import constants, db
from info.models import User, News, Category
from info.modules import news
from info.modules.admin import admin_blu
from info.utils.common import user_login_data
from info.utils.image_storage import storage
from info.utils.response_code import RET

@admin_blu.route('/news_type', methods=["GET", "POST"])
def news_type():

    if request.method == "GET":
        # 查询分类数据
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_type.html', errmsg="查询数据错误")

        category_dict_li = []
        for category in categories:
            # 取到分类的字典
            cate_dict = category.to_dict()
            category_dict_li.append(cate_dict)

        # 移除最新的分类
        category_dict_li.pop(0)

        data = {
            "categories": category_dict_li
        }

        return render_template('admin/news_type.html', data=data)

    # 新增或者添加分类
    # 1. 取参数
    cname = request.json.get("name")
    # 如果传了cid，代表是编辑已存在的分类
    cid = request.json.get("id")

    if not cname:
        return jsonify(error=RET.PARAMERR, errmsg="参数错误")

    if cid:
        # 有 分类 id 代表查询相关数据
        try:
            cid = int(cid)
            category = Category.query.get(cid)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(error=RET.PARAMERR, errmsg="参数错误")

        if not category:
            return jsonify(error=RET.NODATA, errmsg="未查询到分类数据")
        category.name = cname
    else:
        category = Category()
        category.name = cname
        db.session.add(category)

    return jsonify(error=RET.OK, errmsg="OK")

@admin_blu.route('/news_edit_detail', methods=['POST', 'GET'])
def news_edit_detail():

    if request.method == "GET":
        # 查询点击的新闻的相关数据并传入到模板中
        news_id = request.args.get("news_id")

        if not news_id:
            abort(404)

        try:
            news_id = int(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg="参数错误")

        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg="查询数据错误")

        if not news:
            return render_template('admin/news_edit_detail.html', errmsg="未查询到数据")

        # 查询分类数据
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg="查询数据错误")

        category_dict_li = []
        for category in categories:
            # 取到分类的字典
            cate_dict = category.to_dict()
            # 判断当前遍历到的分类是否是当前新闻的分类，如果是，则添加is_selected为true
            if category.id == news.category_id:
                cate_dict["is_selected"] = True
            category_dict_li.append(cate_dict)

        # 移除最新的分类
        category_dict_li.pop(0)

        data = {
            "news": news.to_dict(),
            "categories": category_dict_li
        }

        return render_template('admin/news_edit_detail.html', data=data)

    # 取到Post进来的数据
    news_id = request.form.get("news_id")
    title = request.form.get("title")
    digest = request.form.get("digest")
    content = request.form.get("content")
    index_image = request.files.get("index_image")
    category_id = request.form.get("category_id")
    # 1.1 判断数据是否有值
    if not all([title, digest, content, category_id]):
        return jsonify(error=RET.PARAMERR, errmsg="参数有误")

    # 查询指定id的
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(error=RET.DBERR, errmsg="数据查询失败")

    if not news:
        return jsonify(error=RET.NODATA, errmsg="未查询到新闻数据")

    # 1.2 尝试读取图片
    if index_image:
        try:
            index_image = index_image.read()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(error=RET.PARAMERR, errmsg="参数有误")

        # 2. 将标题图片上传到七牛
        try:
            key = storage(index_image)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(error=RET.THIRDERR, errmsg="上传图片错误")
        news.index_image_url = constants.QINIU_DOMIN_PREFIX + key

    # 3. 设置相关数据
    news.title = title
    news.digest = digest
    news.content = content
    news.category_id = category_id

    return jsonify(error=RET.OK, errmsg="OK")

@admin_blu.route('/news_edit')
def news_edit():
    '''
    新闻编辑
    :return:
    '''
    page = request.args.get('p', 1)
    keywords = request.args.get('keywords', None)

    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    filters = [News.status == 0]
    # 如果添加关键字， 那么就添加关键字搜索
    if keywords:
        filters.append(News.title.contains(keywords))
    try:
        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()) \
            .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)
        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_page.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_basic_dict())

    context = {
        'total_page': total_page,
        'current_page': current_page,
        'news_list': news_dict_list
    }

    return render_template('admin/news_edit.html', data =context)

@admin_blu.route('/news_review_action', methods=['POST'])
def news_review_action():
    # 1.接收参数
    news_id = request.json.get('news_id')
    action = request.json.get('action')
    # 2.参数校验
    if not all([news_id, action]):
        return jsonify(error=RET.PARAMERR, errmsg='参数错误')
    if action not in ('accept', 'reject'):
        return jsonify(error=RET.PARAMERR, errmsg='参数错误')
    # 查询到指定的新闻数据
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(error=RET.DBERR, errmsg='数据查询失败')
    if action == 'accept':
        # 代表接受
        news.status = 0
        # 代表拒绝
        reason = request.json.get('reason')
        if not reason:
            return jsonify(error=RET.PARAMERR, ermsg='请输入拒绝原因')
        news.status = -1
        news.reason = reason

    return jsonify(error=RET.OK, errmsg='OK')

@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    '''
    新闻审核
    :param news_id:
    :return:
    '''
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    if not news:
        return  render_template('admin/news_review_detail.html', data={'errmsg': '未查到此新闻'})

    # 返回数据
    data = {
        'news': news.to_dict()
    }
    return render_template('admin/news_review_detail.html', data=data)

@admin_blu.route('/news_review')
def news_review():
    '''
    返回待审核新闻列表
    :return:
    '''
    page = request.args.get('p', 1)
    keywords = request.args.get('keywords', None)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    filters = [News.status != 0]
    # 如果关键字存在， 那么就添加关键字搜索
    if keywords:
        filters.append(News.title.contains(keywords))
    try:
        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()) \
            .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_review_dict())

    context = {
        'total_page' : total_page,
        'current_page' : current_page,
        'news_list' : news_dict_list
    }

    return render_template('admin/news_review.html', data=context)

@admin_blu.route('/user_list')
@user_login_data
def user_list():
    '''
    用户列表
    :return:
    '''
    page = request.args.get('page', 1)

    try:
        page= int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    users = []
    current_page = 1
    total_page = 1

    try:
        paginate = User.query.filter(User.is_admin==False).paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        users = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_page.logger.error(e)

    # 进行模型列表转字典
    user_dict_li =[]
    for user in users:
        user_dict_li.append(user.to_admin_dict())

    data = {
        'users' : user_dict_li,
        'total_page' : total_page,
        'current_page' : current_page
    }

    return render_template('admin/user_list.html', data=data)

@admin_blu.route('/user_count')
@user_login_data
def user_count():
    '''
    用户统计
    :return:
    '''
    # 总人数
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    # 月新增数
    mon_count = 0
    t = time.localtime()
    begin_mon_date_str = '%d-%02d-01' % (t.tm_year, t.tm_mon)
    # 将字符串转成datetime对象
    begin_mon_date = datetime.strptime("2018-08-01", "%Y-%m-%d")
    try:
        mon_count = User.query.filter(User.is_admin == False, User.create_time > begin_mon_date).count()
    except Exception as e:

info/modules/index/__init__.py
from flask import Blueprint

# 创建蓝图对象
index_blu = Blueprint('index', __name__)

from . import views

info/modules/index/views.py
from flask import render_template, current_app, session, request, jsonify
# from info import redis_store
from info.constants import CLICK_RANK_MAX_NEWS
from info.models import User, News, Category
from info.utils.response_code import RET
from . import index_blu


@index_blu.route('/news_list')
def news_list():
    '''
    获取首页新闻数据
    :return:
    '''
    # 1.获取参数
    # 新闻的分类id
    cid = request.args.get('cid', '1')
    page = request.args.get('page', '1')
    per_page = request.args.get('per_page', '10')
    # 2.校验参数
    try:
        page = int(page)
        cid = int(cid)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(error=RET.PARAMERR, errmsg='参数错误')

    filters = [News.status == 0]
    if cid != 1: # 查询的不是最新的数据
        # 需要添加条件
        filters.append(News.category_id == cid)
    # 3.查询数据
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)

    except Exception as e:
        current_app.logger.error(e)
        return jsonify(error=RET.DBERR, errmsg='数据查询错误')
    # 取到当前页的数据
    news_model_list = paginate.items
    total_page = paginate.pages
    current_page = paginate.page
    # 将模型对象列表转换成字典
    new_dict_li = []
    for news in news_model_list:
        new_dict_li.append(news.to_basic_dict())


    data = {
        'total_page':total_page,
        'current_page':current_page,
        'news_dict_li': new_dict_li,
    }
    return jsonify(error=RET.OK, errmsg='ok', data = data)


@index_blu.route('/')
def index():
    # session['name'] = 'itheima'

    # 测试打印日志

    # current_app.logger.debug('测试debug')
    # current_app.logger.error('测试error')
    # current_app.logger.fatal('测试fatal')

    # 向 redis 中保存一个字 name itcast
    # 获取当前用户登陆的信息
    # 显示用户是否登录的逻辑
    user_id = session.get('user_id', None)
    # 通过id获取当前用户的信息
    user = None
    if user_id:
        try:
            user = User.query.get(user_id)
        except Exception as e:
            current_app.logger.error(e)

    # 右侧新闻排行的逻辑
    news_list = []
    try:
        news_list = News.query.order_by(News.clicks.desc()).limit(CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
    # 定义一个空的字典列表，里面装的就是字典
    news_dict_li = []
    # 遍历对象列表，将对象的字典添加到字典列表当中
    for news in news_list:
        news_dict_li.append(news.to_basic_dict())
    # 查询分类数据，通过模板的形式渲染出来
    categories= Category.query.all()

    category_li = []
    for category in categories:
        category_li.append(category.to_dict())

    # print(user.to_dict())
    data = {
        'user': user.to_dict() if user else None,
        'news_dict_li': news_dict_li,
        'category_li': category_li
    }
    return render_template('news/index.html', data=data)


# 在打开网页的时候，浏览器会默认请求根路径 + favicon.ico 作为网站标签的小图标
@index_blu.route('/favicon.ico')
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/modules/news/__init__.py
from flask import Blueprint

# 创建蓝图对象
news_blu = Blueprint('news', __name__, url_prefix= '/news')

from . import views

info/modules/passport/__init__.py
# 登录注册相关的业务逻辑都放置在当前模块
from flask import Blueprint

# 创建蓝图对象
passport_blu = Blueprint('passport', __name__ , url_prefix= '/passport')

from . import views

info/modules/profile/__init__.py
# 登录注册相关的业务逻辑都放置在当前模块
from flask import Blueprint

# 创建蓝图对象
profile_blu = Blueprint('profile', __name__ , url_prefix= '/user')

from . import views

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    {% block cssBlock %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}

    {% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block categoryBlock %}
                <ul class="menu fl">
                    {% for category in data.category_li %}
                        {% if loop.index == 1 %}
                            <li data-cid="{{ category.id }}" class="active"><a href="javascript:;">{{ category.name }}</a></li>
                        {% else %}
                            <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endblock %}
            {% if data.user %}
                <!-- 用户登录后显示下面，隐藏上面 -->
                <div class="user_login fr">
                    <img src="{% if data.user.avatar_url %} {{ data.user.avatar_url }} {% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                    <a href="{{ url_for('profile.user_info') }}" id="nick_name">{{ data.user.nick_name }}</a>
                    <a href="javascript:;" onclick="logout()">退出</a>
                </div>
            {% else %}
                <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
            {% endif %}


        </div>
    </div>

    <div class="conter_con">
        {% block contentBlock %}

        {% endblock %}

        {% block rankBlock %}
            <div class="rank_con fr">
                {% block authorBlock %}

                {% endblock %}

                <div class="rank_title">
                    <h3>点击排行</h3>
                </div>
                <ul class="rank_list">
                    {% for news in data.news_dict_li %}
                        <li><span class="{{ loop.index0 | index_class }}">{{ loop.index }}</span><a href="#">{{ news.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endblock %}

    </div>

    {% block bottomBlock %}
        <div class="footer">
            <div class="footer_links">
                <a href="">关于我们</a>
                <span>|</span>
                <a href="">联系我们</a>
                <span>|</span>
                <a href="">招聘人才</a>
                <span>|</span>
                <a href="">友情链接</a>
            </div>
            <p class="copyright">
                CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
    电话：010-****888    京ICP备*******8号
            </p>
        </div>
    {% endblock %}

    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/index.html
{% extends 'news/base.html' %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block contentBlock %}
<ul class="list_con fl">

</ul>
{% endblock %}

info/templates/news/other.html
{% extends "news/base.html" %}

{% block titleBlock %}
用户概况
{% endblock %}

{% block cssBlock %}
<link rel="stylesheet" type="text/css" href="../../static/news/css/jquery.pagination.css">
{% endblock %}

{% block scriptBlock %}

<script type="text/javascript" src="../../static/news/js/jquery.pagination.min.js"></script>
<script type="text/javascript" src="../../static/news/js/other.js"></script>
{% endblock %}

{% block contentBlock %}
    <div class="user_menu_con fl">
        <div class="user_center_pic">
            <img src="{% if data.other_info.avatar_url %}
            {{ data.other_info.avatar_url }}
            {% else %}
            ../../static/news/images/user_pic.png
            {% endif %}" alt="用户图片">
        </div>
        <div class="user_center_name">{{ data.other_info.nick_name }}</div>

        <ul class="other_detail">
            <li>性 别：{% if data.other_info.gender == "MAN" %}男
            {% else %}女
            {% endif %}</li>
            <li>签 名：{% if data.other_info.signature %}
                {{ data.other_info.signature }}
            {% else %}
                这个人很懒，什么都没留下
            {% endif %}</li>
        </ul>

        <div class="focus_other">
            <a href="javascript:;" class="focus block-center" data-userid="{{ data.other_info.id }}" style="display: {% if data.is_followed %}none
            {% else %}block
            {% endif %}">关注</a><br>
            <a href="javascript:;" class="focused block-center" data-userid="{{ data.other_info.id }}" style="display: {% if data.is_followed %}block
            {% else %}none
            {% endif %}"><span class="out">已关注</span><span class="over">取消关注</span></a>
        </div>

    </div>

    <div class="user_con fr">
            <div class="other_collect">
                <h3>他的文章</h3>
                <ul class="article_list">
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                    <li><a href="#">智能音箱“不智能”：这次轮到三星语音助手Bixby被吐槽了</a><span>2018-1-17</span></li>
                </ul>

                <div id="pagination" class="page"></div>
                <script>
                    $(function(){
                        $("#pagination").pagination({
                            currentPage: 2,
                            totalPage: 3,
                            callback: function(current) {
                                getNewsList(current)
                            }
                        });
                    });
                </script>
            </div>

        </div>
{% endblock %}

{% block rankBlock %}
{% endblock %}

info/templates/news/user.html
{% extends 'news/base.html' %}

{% block titleBlock %}
用户中心
{% endblock %}

{% block rankBlock %}

{% endblock %}

{% block authorBlock %}
{% endblock %}

{% block contentBlock %}
    <div class="user_menu_con fl">
			<div class="user_center_pic">
                <img src={% if data.user.avatar_url %}
                    {{ data.user.avatar_url }}
                {% else %}
                    "../../static/news/images/user_pic.png"
                {% endif %} alt="用户图片">
			</div>
			<div class="user_center_name">{{ data.user.nick_name }}</div>

			<ul class="option_list">
				<li class="active"><a href="{{ url_for("profile.base_info") }}" target="main_frame">基本资料</a></li>
				<li><a href="{{ url_for('profile.pic_info') }}" target="main_frame">头像设置</a></li>
				<li><a href="{{ url_for('profile.user_follow') }}" target="main_frame">我的关注</a></li>
				<li><a href="{{url_for('profile.pass_info')}}" target="main_frame">密码修改</a></li>
				<li><a href="{{url_for('profile.user_collection')}}" target="main_frame">我的收藏</a></li>
				<li><a href="{{ url_for('profile.news_release') }}" target="main_frame">新闻发布</a></li>
				<li><a href="{{ url_for('profile.news_list') }}" target="main_frame">新闻列表</a></li>
			</ul>
		</div>

    <div class="user_con fr">
			<iframe src="{{ url_for("profile.base_info") }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
		</div>
{% endblock %}

{% block categoryBlock %}
{% endblock %}